# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tnishop.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pymongo
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TNISHOP(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(407, 295)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textIdProduct = QtWidgets.QTextEdit(Dialog)
        self.textIdProduct.setGeometry(QtCore.QRect(120, 20, 261, 31))
        self.textIdProduct.setObjectName("textIdProduct")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textName = QtWidgets.QTextEdit(Dialog)
        self.textName.setGeometry(QtCore.QRect(120, 100, 261, 31))
        self.textName.setObjectName("textName")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textPrice = QtWidgets.QTextEdit(Dialog)
        self.textPrice.setGeometry(QtCore.QRect(120, 140, 261, 31))
        self.textPrice.setObjectName("textPrice")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.textStock = QtWidgets.QTextEdit(Dialog)
        self.textStock.setGeometry(QtCore.QRect(120, 180, 261, 31))
        self.textStock.setObjectName("textStock")
        self.comboBoxCat = QtWidgets.QComboBox(Dialog)
        self.comboBoxCat.setGeometry(QtCore.QRect(120, 61, 261, 31))
        self.comboBoxCat.setObjectName("comboBoxCat")
        self.comboBoxCat.addItem("")
        self.comboBoxCat.addItem("")
        self.comboBoxCat.addItem("")
        self.comboBoxCat.addItem("")
        self.btnSave = QtWidgets.QPushButton(Dialog)
        self.btnSave.setGeometry(QtCore.QRect(10, 230, 121, 41))
        self.btnSave.setToolTip("")
        self.btnSave.setObjectName("btnSave")
        self.btnReset = QtWidgets.QPushButton(Dialog)
        self.btnReset.setGeometry(QtCore.QRect(140, 230, 121, 41))
        self.btnReset.setToolTip("")
        self.btnReset.setObjectName("btnReset")
        self.btnShowBMI = QtWidgets.QPushButton(Dialog)
        self.btnShowBMI.setGeometry(QtCore.QRect(270, 230, 121, 41))
        self.btnShowBMI.setToolTip("")
        self.btnShowBMI.setObjectName("btnShowBMI")

        self.btnSave.clicked.connect(self.insertData)
        self.btnReset.clicked.connect(self.reset)
        self.btnShowBMI.clicked.connect(self.openBMI)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TNI Shop"))
        self.label.setText(_translate("Dialog", "รหัสสินค้า"))
        self.label_2.setText(_translate("Dialog", "ประเภทสินค้า"))
        self.label_3.setText(_translate("Dialog", "ชื่อ"))
        self.label_4.setText(_translate("Dialog", "ราคา"))
        self.label_5.setText(_translate("Dialog", "สินค้าคงคลัง"))
        self.comboBoxCat.setItemText(0, _translate("Dialog", "ขนม"))
        self.comboBoxCat.setItemText(1, _translate("Dialog", "อาหาร"))
        self.comboBoxCat.setItemText(2, _translate("Dialog", "น้ำ"))
        self.comboBoxCat.setItemText(3, _translate("Dialog", "ยา"))
        self.btnSave.setText(_translate("Dialog", "บันทึก"))
        self.btnReset.setText(_translate("Dialog", "Reset"))
        self.btnShowBMI.setText(_translate("Dialog", "เปิด BMI"))

    def insertData(self):
        connectTNIMongoDB = 'mongodb+srv://adisak:RPGnqPNGypIy6bQJ@cluster0.ffnxq.mongodb.net/<dbname>?retryWrites=true&w=majority'
        id = self.textIdProduct.toPlainText()
        cat = self.comboBoxCat.currentText()
        name = self.textName.toPlainText()
        price = float(self.textPrice.toPlainText())
        stock = float(self.textStock.toPlainText())
        with pymongo.MongoClient(connectTNIMongoDB) as conn:
            db = conn.get_database('TniShop')
            data = {'id': id, 'type': cat, 'name': name, 'price': price, 'stock': stock}
            db['Products'].insert_one(data)
        self.reset()

    def reset(self):
        self.textIdProduct.clear()
        self.comboBoxCat.setCurrentIndex(0)
        self.textName.clear()
        self.textPrice.clear()
        self.textStock.clear()
        self.textIdProduct.setFocus()

    def openBMI(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = bmi.Ui_BMI()
        self.ui.setupUi(self.window)
        self.window.show()



if __name__ == "__main__":
    import sys
    import bmi

    app = QtWidgets.QApplication(sys.argv)
    tnishop = QtWidgets.QDialog()
    ui = Ui_TNISHOP()
    ui.setupUi(tnishop)
    tnishop.show()
    sys.exit(app.exec_())
